# Generated by Django 5.2.8 on 2026-04-07 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('company', '0003_job_external_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Aguardando'), ('viewed', 'Visualizado'), ('accepted', 'Aprovado'), ('rejected', 'Reprovado')], default='pending', max_length=20)),
                ('experience_rating', models.IntegerField(blank=True, null=True)),
                ('experience_comment', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='company.job')),
            ],
            options={
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
