# Generated by Django 5.2.8 on 2026-04-07 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
    ]
