# Generated by Django 5.2.8 on 2026-04-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_remove_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='hard_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='soft_skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
