# Generated by Django 5.2.8 on 2026-04-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidateprofile_hard_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cv',
            field=models.FileField(blank=True, upload_to='cvs/'),
        ),
    ]
