# Generated by Django 5.2.8 on 2026-04-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_jobapplication_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
