# Generated by Django 5.2.8 on 2026-04-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_add_is_archived_to_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='desired_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('medio', 'Ensino Médio'), ('superior_incompleto', 'Superior Incompleto'), ('superior_completo', 'Superior Completo'), ('pos_graduacao', 'Pós-graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='github_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='hidden_hard_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='hidden_soft_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_cv',
            field=models.FileField(blank=True, null=True, upload_to='profile_cvs/'),
        ),
    ]
