# Generated by Django 5.2.8 on 2026-04-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_add_desired_area_seniority'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='languages',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
