# Generated by Django 5.2.8 on 2026-04-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_add_languages_portfolio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='scout_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='company_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='company_rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='company_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
