# Generated by Django 5.2.8 on 2026-04-07 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Tempo integral'), ('part_time', 'Meio período'), ('internship', 'Estágio')], default='full_time', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('paused', 'Pausada'), ('closed', 'Fechada')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company.companyprofile')),
            ],
        ),
    ]
