# Generated by Django 5.2.8 on 2026-04-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='external_url',
            field=models.URLField(blank=True),
        ),
    ]
