# Generated by Django 5.2.8 on 2026-04-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_job_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_hard_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='required_soft_skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
