# Generated by Django 5.2.8 on 2026-04-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_job_required_hard_skills_job_required_soft_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_area',
            field=models.CharField(blank=True, choices=[('backend', 'Desenvolvimento Backend'), ('frontend', 'Desenvolvimento Frontend'), ('fullstack', 'Desenvolvimento Full Stack'), ('mobile', 'Desenvolvimento Mobile'), ('data_science', 'Data Science / Machine Learning'), ('data_eng', 'Engenharia de Dados'), ('devops', 'DevOps / SRE / Cloud'), ('security', 'Segurança da Informação'), ('qa', 'QA / Testes'), ('ux', 'UX / Design de Produto'), ('product', 'Gerência de Produto (PM)'), ('bi', 'BI / Analytics'), ('infra', 'Suporte / Infraestrutura'), ('project_mgmt', 'Gestão de Projetos / Scrum Master'), ('other', 'Outro')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='seniority',
            field=models.CharField(blank=True, choices=[('estagio', 'Estágio'), ('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior'), ('especialista', 'Especialista / Staff'), ('gestao', 'Gerência / Tech Lead')], default='', max_length=20),
        ),
    ]
