# Generated by Django 5.2.8 on 2026-04-12 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_add_desired_area_seniority'),
        ('company', '0005_add_job_area_seniority'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1_10', '1 – 10 funcionários'), ('11_50', '11 – 50 funcionários'), ('51_200', '51 – 200 funcionários'), ('201_500', '201 – 500 funcionários'), ('500_plus', 'Mais de 500 funcionários')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CompanyFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='candidates.candidateprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='company.companyprofile')),
            ],
            options={
                'unique_together': {('candidate', 'company')},
            },
        ),
    ]
