# Generated by Django 5.2.8 on 2026-04-13 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_add_company_rating_and_scout_score'),
        ('company', '0006_add_profile_fields_and_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='candidates.candidateprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_endorsements', to='company.companyprofile')),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='candidates.jobapplication')),
            ],
            options={
                'unique_together': {('job_application', 'skill_name')},
            },
        ),
    ]
